stages:
  - lint
  - test

before_script:
  - git fetch --all
  - npm install 

lint:
  stage: lint
  script:
    - npm run lint
  only
    - master

test:
  stage: test
  script:
    - npm run test
  only
    - master