name: check
on: [push]
jobs:
  check_job:
    runs-on: ubuntu-latest
    name: check
    steps:
    - name: Checkout    
      uses: actions/checkout@v2 
      
    - name: Install Dependencies
      run: npm install
    - name: lint
      run: npm lint
    - name: test
      run: npm test

